spring:
    application:
        name: zuul-gateway
server:
    port: 55555
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:11111/eureka/, http://localhost:11112/eureka/, http://localhost:11113/eureka/


zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:3333/