spring:
    application:
        name: api-gateway
server:
    port: 5555
eureka:
    client:
        serviceUrl:
            defaultZone: http://www.zkgengkun.com:1111/eureka/


zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://www.zkgengkun.com:3333/