spring:
  application:
    name: ra-server
server:
  port: 11111
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:11112/eureka/, http://localhost:11113/eureka/