spring:
  application:
    name: shik-ra-server
server:
  port: 1111
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://www.zkgengkun.com:1112/eureka/,http://www.zkgengkun.com:1113/eureka/