spring:
    application:
        name: shik-zuul-gateway
server:
    port: 5552
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/


zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:3333/