server:
  port: 8882

spring:
  application:
    name: shik-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zkgengkun/shik/
          searchPaths: shik-common/config-repo
          username: username
          password: password
      discovery:
        enabled: true
  rabbitmq:
    addresses: localhost:5672
    username: root
    password: qweASDzxc

security:
  user:
    name: shik
    password: shik-config-server

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/
