spring:
  application:
    name: shik-config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/shik_geng/shik/
          searchPaths: shik-common/config-repo
          username: username
          password: password
      discovery:
        enabled: true
  rabbitmq:
    addresses: www.zkgengkun.com:5672
    username: root
    password: 123!@#qwe

server:
  port: 8882

security:
  user:
    password: shik-config-server

eureka:
    client:
        serviceUrl:
            defaultZone: http://www.zkgengkun.com:1111/eureka/,http://www.zkgengkun.com:1112/eureka/,http://www.zkgengkun.com:1113/eureka/
