spring:
  application:
    name: shik-ra
server:
  port: 1112
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 120.76.147.141
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
