spring:
  application:
    name: shik-config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/shik_geng/shik/
          searchPaths: shik-common/config-repo
          username: username
          password: password

server:
  port: 8888

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/
  
# git管理配置
