spring:
  application:
    name: ra-server
server:
  port: 11112
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:11113/eureka/, http://localhost:11111/eureka/