spring:
  application:
    name: shik-ra-server
server:
  port: 1112
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:1113/eureka/,http://localhost:1111/eureka/