spring:
  application:
    name: ra-server
server:
  port: 1113
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/