spring:
  application:
    name: shik-ra
server:
  port: 1111
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 47.52.232.4
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1112/eureka/
  server:
    eviction-interval-timer-in-ms: 60000
